### ISSUE TITLE
iosにて任意のタイミングでsetDeviceTokenを呼び出した際にinstallationの登録ができない

### ISSUE THREAD

**Issue by tyatya1229** [NIFCLOUD-mbaas/monaca_push_plugin#110]
不具合の概要(Description of bug)
初期起動時にはsetDeviceTokenを利用して、DeviceTokenをAPNSから取得し、ニフクラのinstallationへの登録が行ないます。その他にアプリの設定画面などでプッシュ通知のON/OFFをスイッチさせるような機能があり、ニフクラのinstallationを再登録（setDeviceToken）させたりinstallationを削除（installation.delete）したりを制御するようにしております。後者のプッシュ通知をONに再設定した際にsetDeviceTokenを呼び出しを行うとinstallationへの登録ができません。

おそらく、initialize時にはDeviceTokenをsetDeviceTokenAPNSにてセットされて正しく登録されますが、initialize以外でsetDeviceTokenを呼び出すと下記にてDeviceTokenのセットする部分が無くなったことにより、DeveiceTokenのセットが無い状態となり、登録ができないのではないかとおもっております。
https://github.com/NIFCLOUD-mbaas/monaca_push_plugin/commit/5050c8d209dcea459c87f4356666d6edfd480c47

- SDKのバージョン(SDK version)：3.0.9
- 不具合が発生した環境(Environment requirement)：ios14.0
- 不具合を再現させる手順・サンプルコード(Step for Reproduce bug / Sample code)
  - 1. 初期起動でsetDeviceTokenをinstallationを登録　⇒ installationは登録できる
  - 2. ボタン操作などから登録したinstallationを取得し、deleteから削除をする　⇒ installationは削除できる
  - 3. ボタン操作などからsetDeviceTokenを呼び出し、installationを登録　⇒　ここでinstallationの登録ができない
- エラーメッセージ(Error messages)
  - エラーメッセージはなく、ニフクラのinstallationへの登録がされない。

**Comment by ncmbadmin** [comment]
お世話になっております、issue作成いただき、ありがとうございます。

順次、優先付けを行ったうえで対応いたしますので、
今しばらくお待ちいただきますようお願いいたします。
対応次第、こちらの issue にて報告いたします。

今後とも、mobile backend をどうぞよろしくお願いいたします。
