### ISSUE TITLE
Where to find the keys?

### ISSUE THREAD

**Issue by phiasco12** [NIFCLOUD-mbaas/monaca_push_plugin#112]
Sorry this is not a bug but rather a question.

I'm trying to use this plugin but I can't figure out how.

I've used cordova firebase plugin before successfully but this plugin is slightly different.

Can you please let me know what this is and where to get the information required to fill-in these details: 

```
 NCMB.monaca.setDeviceToken(
                    "#####application_key#####",
                    "#####client_key#####"
                );
```

more specifically, where do I need to find the` application_key` and `client_key` in my firebase account? I cannot see anything like that in my firebase account.

Thanks

**Comment by ncmbadmin** [comment]
Thank you for your support, the following procedure is how to use monaca-push-plugin. Please refer.
https://mbaas.nifcloud.com/doc/current/introduction/div_quickstart_javascript_monaca.html
If you have any questions, please use the following user community.
https://github.com/NIFCLOUD-mbaas/UserCommunity
We look forward to your continued support of mobile backend.

**Comment by ncmbadmin** [comment]
Thank you.
We have already answered here, so we will close this issue.
Anyway, thank you for your mobile backend.
