### ISSUE TITLE
ニフクラのiOSアプリバージョン

### ISSUE THREAD

**Issue by stcanbe** [NIFCLOUD-mbaas/monaca_push_plugin#130]
## 不具合の概要(Description of bug)

ニフクラに表示されるiOSのアプリバージョンが、
アプリのバージョンではなくバンドルバージョンになります。

下記のコードを修正することで、ニフクラにアプリのバージョンが表示されます。

monaca_push_plugin/src/ios/NCMB/NCMBInstallation.m　73行目
```
[installation setObject:[[[NSBundle mainBundle] infoDictionary] objectForKey:@"CFBundleVersion"]
　　↓
[installation setObject:[[[NSBundle mainBundle] infoDictionary] objectForKey:@"CFBundleShortVersionString"]
```

monaca_push_plugin/src/ios/NCMB/NCMBInstallation.m　100行目
```
NSString *newAppVer = [[[NSBundle mainBundle] infoDictionary] objectForKey:@"CFBundleVersion"];
　　↓
NSString *newAppVer = [[[NSBundle mainBundle] infoDictionary] objectForKey:@"CFBundleShortVersionString"];
```

**Comment by ncmbadmin** [comment]
お世話になっております、issue作成いただき、ありがとうございます。

順次、優先付けを行ったうえで対応いたしますので、
今しばらくお待ちいただきますようお願いいたします。
対応次第、こちらの issue にて報告いたします。

今後とも、mobile backend をどうぞよろしくお願いいたします。

**Comment by ncmbadmin** [comment]
お世話になっております。
本 issue について、不具合でなく仕様ではありますがドキュメントに詳細を記載していなかったため記載しました。
ご報告ありがとうございました。
詳細は以下のドキュメントにてご確認ください。
https://mbaas.nifcloud.com/doc/current/push/basic_usage_javascript.html#Monaca%20%E5%81%B4%E3%81%AE%E8%A8%AD%E5%AE%9A
今後とも、mobile backend をどうぞよろしくお願いいたします。
