### ISSUE TITLE
プッシュ受信後に、NCMB.monaca.setHandlerメソッドで送信時にセットしたjsonパラメータが取得できますが、iOSのみpayload全体(タイトルやメッセージ本文も含め)が取得されます。

### ISSUE THREAD

**Issue by oonoyosp** [NIFCloud-mbaas/monaca_push_plugin#30]
## 不具合の概要(Description of bug)
（お客様からの不具合報告）
[iOSのみ]プッシュ受信後に、NCMB.monaca.setHandlerメソッドで送信時にセットしたjsonパラメータが取得できますが、iOSのみpayload全体(タイトルやメッセージ本文も含め)が取得されます。

- SDKのバージョン(SDK version)
monaca_push_plugin-2.0.5

- 不具合が発生した環境(Environment requirement)
iOS10.3.1
- 不具合を再現させる手順・サンプルコード(Step for Reproduce bug / Sample code)

- エラーメッセージ(Error messages)

**Comment by ncmbadmin** [comment]
ご報告いただき、ありがとうございます。
動作確認させていただき、現象を確認いたしました。

* jsonパラメーターを指定しない場合の結果
```
{"aps":{"alert":{"title":null, "body":"test"}, "sound":"default"}, "ApplicationStateActive":false, "com.nifty.PushId":"*********"}
```
* jsonパラメーター `{"key":"value"}` を指定した場合の結果
```
{"aps":{"alert":{"title":null, "body":"test"}, "sound":"default"}, "ApplicationStateActive":false, "com.nifty.PushId":"*********", "key":"value"}
```

こちらの現象はiOS SDKでも発生していて、以前からのiOS プッシュ通知の仕様です。
また、メッセージなどの情報が取得される場合は、お客様へ影響が不利な状況ではないので不具合ではないと判断させていただきます。

従って、本件クローズさせていただきます。
今後とも、どうぞよろしくお願いいたします。
