### ISSUE TITLE
jsonパラメータのkeyに"title"のようなpayloadに存在するkeyを指定、値に使用する型を配列等にすると、通知画面が表示されません。

### ISSUE THREAD

**Issue by oonoyosp** [NIFCloud-mbaas/monaca_push_plugin#31]
## 不具合の概要(Description of bug)
（お客様からの不具合報告）
[iOSのみ]jsonパラメータのkeyに"title"のようなpayloadに存在するkeyを指定、値に使用する型を配列等にすると、通知画面が表示されません。

- SDKのバージョン(SDK version)
monaca_push_plugin-2.0.5
- 不具合が発生した環境(Environment requirement)
iOS10.3.1
- 不具合を再現させる手順・サンプルコード(Step for Reproduce bug / Sample code)
- エラーメッセージ(Error messages)

**Comment by ncmbadmin** [comment]
ご報告いただき、ありがとうございます。
以下のように、動作確認させていただきましたが、再現することは出来ませんでした。

* ケース１：
  - title: 設定なし
  - message: "テスト"
  - JSON: `{"title": "Test tile json"}`
* ケース１：
  - title: "Test title set"
  - message: "テスト"
  - JSON: `{"title": "Test title json"}`

上記の2件とも、プッシュ通知が正常に表示され、JSONに設定したtitle値が影響されず、
titleに設定した値の通り（未設定場合はタイトル表示なし）となっています。
従って、本件は正常動作と判断させていただきます。

本件クローズさせていただきます。
今後とも、どうぞよろしくお願いいたします
