### ISSUE TITLE
【機能追加要望】androidプッシュ受信時のダイアログ表示

### ISSUE THREAD

**Issue by nakamuraakua** [NIFCLOUD-mbaas/monaca_push_plugin#5]
android端末でプッシュを受信したときのダイアログ表示を
monacaプラグインでも使えるようにしていただきたいです。

**Comment by ncmbadmin** [comment]
お世話になっております、issue作成いただき、ありがとうございました。
Android 10 (Android Q)から、[バックグラウンドアクティビティ制限](https://developer.android.com/about/versions/10/privacy/changes#background-activity-starts) により、  
ダイアログプッシュ通知機能は対応しておりません。そのため本issueはcloseとさせていただきます。
今後とも、mobile backend をどうぞよろしくお願いいたします。
