### ISSUE TITLE
アプリ起動中に通知が表示されない

### ISSUE THREAD

**Issue by morisatoru** [NIFCloud-mbaas/monaca_push_plugin#75]
## 不具合の概要(Description of bug)

アプリ再起動後に iOS プッシュ通知を受け取った場合、アプリ起動中に通知が表示されません。

- SDKのバージョン(SDK version)
    - ver.2.0.10 以降
- 不具合が発生した環境(Environment requirement)
    - iOS 用にプッシュ通知機能を実装したアプリ

**Comment by ncmbadmin** [comment]
本件リリースによって、issue解消されましたので、クローズさせていただきます。
