### ISSUE TITLE
保証可能な Cordova バージョンの変更

### ISSUE THREAD

**Issue by morisatoru** [NIFCloud-mbaas/monaca_push_plugin#78]
## 概要(Description)

- monaca push plugin v3.0.0 において `ncmb.gradle` について、 `dependencies` の表現を APIレベル26 に則した表現に変更した。
- このことにより、Cordova バージョン 6.5 では対応できない問題があるが、Google Play Store では APIレベル26 以上を必須としているため、 `ncmb.gradle` については変更せず動作保証範囲を変更する。

**Comment by ncmbadmin** [comment]
本件リリースによって、issue解消されましたので、クローズさせていただきます。
