### ISSUE TITLE
Android用プラグイン：AndroidX更新

### ISSUE THREAD

**Issue by ncmbadmin** [NIFCLOUD-mbaas/monaca_push_plugin#98]
Android SDKでは以下のように更新する予定です。
以下の内容と合わせて、更新検討よろしくお願いいたします。
https://github.com/NIFCLOUD-mbaas/ncmb_android/issues/204

### 概要

現在内部Android SDKではAndroid Support Libraryを利用していますが、
以下のドキュメントにより、今後Android Support Libraryの更新はAndroidX（Android Support Libraryの後継）で行われ、AndroidXに移行を推奨しているため、本Android SDKも更新検討を行います。

```
 With the release of Android 9.0 (API level 28) there is a new version of the support library called AndroidX which is part of Jetpack. The AndroidX library contains the existing support library and also includes the latest Jetpack components. 
```
* 参照
https://developer.android.com/topic/libraries/support-library/packages

**Comment by kobo0908** [comment]
こちらでリリース済みのためcloseします。
https://github.com/NIFCLOUD-mbaas/monaca_push_plugin/pull/121
